### ISSUE TITLE
Button hyperlink not working

### ISSUE THREAD

**Issue by meet244** [umeshSinghVerma/Frametagger#7]
When clicking on "Go to the app" button on landing page of website the hyperlink is not there!
![image](https://github.com/user-attachments/assets/9d102cd6-e956-4673-8278-11787b7ffcfd)

I can help to fix this pls assign this to me.

**Comment by umeshSinghVerma** [comment]
Hii @meet244! Thanks for pointing that out! I'll assign the issue to you. Please go ahead and fix the missing hyperlink on the "Go to the app" button. While you're working on that, it would be awesome if you could try out the extension and let me know if you come across any bugs or have suggestions for improvements.

Looking forward to your contribution! 😊 And if you haven’t already, don’t forget to star the repository! 🌟

**Comment by umeshSinghVerma** [comment]
Hi @meet244! 👋

I appreciate your enthusiasm in fixing the bug! However, this issue is relatively minor and might not be considered significant enough for Hacktoberfest. Hacktoberfest generally encourages more substantial contributions that involve new features, major improvements, or considerable bug fixes.

If you're interested in working on a larger issue, feel free to check out the other open issues, such as adding new functionalities or improving the UI. Let me know if you’d like to take on something more challenging, and I'd be happy to assign it to you! 😊

Looking forward to your contributions! 🎉
